const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Arr,
		C3.Plugins.Sprite,
		C3.Plugins.Text,
		C3.Plugins.AJAX,
		C3.Plugins.Mouse,
		C3.Plugins.Touch,
		C3.Plugins.Dictionary,
		C3.Plugins.yagames_adaptivetext,
		C3.Plugins.NinePatch,
		C3.Plugins.LocalStorage,
		C3.Behaviors.scrollto,
		C3.Behaviors.EightDir,
		C3.Plugins.sliderbar,
		C3.Behaviors.Tween,
		C3.Plugins.TextBox,
		C3.Plugins.List,
		C3.Plugins.Browser,
		C3.Plugins.Keyboard,
		C3.Plugins.TiledBg,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Dictionary.Acts.Clear,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.yagames_adaptivetext.Cnds.PickByUID,
		C3.Plugins.yagames_adaptivetext.Acts.SetVisible,
		C3.Plugins.System.Acts.Signal,
		C3.Plugins.System.Cnds.OnSignal,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.Arr.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.System.Cnds.While,
		C3.Plugins.Arr.Cnds.CompareSize,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Arr.Exps.Height,
		C3.Plugins.Arr.Cnds.CompareXY,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Dictionary.Cnds.HasKey,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.Arr.Acts.SetXYZ,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.Dictionary.Acts.AddKey,
		C3.Plugins.Arr.Acts.Shuffle,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.yagames_adaptivetext.Cnds.CompareInstanceVar,
		C3.Plugins.yagames_adaptivetext.Exps.GetText,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.yagames_adaptivetext.Exps.X,
		C3.Plugins.yagames_adaptivetext.Exps.Y,
		C3.Plugins.Arr.Cnds.CompareXYZ,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.NinePatch.Acts.Destroy,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Acts.StopLoop,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.Arr.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Cnds.ForEachOrdered,
		C3.Plugins.yagames_adaptivetext.Acts.SetText,
		C3.Plugins.Arr.Cnds.ArrForEach,
		C3.Plugins.Arr.Exps.CurZ,
		C3.Plugins.Arr.Exps.CurValue,
		C3.Plugins.Dictionary.Exps.Get,
		C3.Plugins.Dictionary.Cnds.CompareCurrentValue,
		C3.Plugins.Arr.Acts.Clear,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Arr.Acts.Sort2,
		C3.Plugins.Arr.Exps.Depth,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Arr.Exps.AsJSON,
		C3.Plugins.NinePatch.Cnds.PickByUID,
		C3.Plugins.NinePatch.Acts.SetDefaultColor,
		C3.Plugins.System.Exps.rgbex255,
		C3.Plugins.NinePatch.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.NinePatch.Exps.UID,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.sliderbar.Acts.SetValue,
		C3.Plugins.sliderbar.Exps.Minimum,
		C3.Plugins.sliderbar.Acts.SetMinimum,
		C3.Plugins.sliderbar.Acts.SetMaximum,
		C3.Plugins.Text.Cnds.PickByUID,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.sliderbar.Exps.Value,
		C3.Plugins.sliderbar.Cnds.OnChanging,
		C3.Plugins.sliderbar.Cnds.OnChanged,
		C3.Plugins.yagames_adaptivetext.Acts.SetInstanceVar,
		C3.Plugins.Dictionary.Exps.KeyCount,
		C3.Plugins.yagames_adaptivetext.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.yagames_adaptivetext.Acts.SetBoolInstanceVar,
		C3.Plugins.yagames_adaptivetext.Acts.AddChild,
		C3.Plugins.yagames_adaptivetext.Cnds.PickChildren,
		C3.Plugins.NinePatch.Cnds.IsOnScreen,
		C3.Plugins.NinePatch.Cnds.IsOutsideLayout,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Behaviors.EightDir.Acts.Stop,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Touch.Exps.AngleAt,
		C3.Behaviors.EightDir.Acts.SetVectorY,
		C3.Plugins.Touch.Exps.SpeedAt,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.System.Exps.viewportheight,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Text.Acts.MoveToTop,
		C3.Plugins.Text.Acts.SetInstanceVar,
		C3.Plugins.Text.Acts.SetFontSize,
		C3.Plugins.Text.Acts.SetHeight,
		C3.Plugins.Text.Exps.TextHeight,
		C3.Plugins.Text.Acts.SetY,
		C3.Plugins.Text.Exps.Height,
		C3.Plugins.Text.Acts.SetFontFace,
		C3.Plugins.Text.Acts.SetBoolInstanceVar,
		C3.Plugins.Text.Cnds.PickChildren,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Text.Exps.BBoxBottom,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Behaviors.EightDir.Acts.SetMaxSpeed,
		C3.Plugins.Sprite.Cnds.PickParent,
		C3.Plugins.yagames_adaptivetext.Acts.Destroy,
		C3.Plugins.yagames_adaptivetext.Acts.MoveToBottom,
		C3.Plugins.Text.Acts.AppendText,
		C3.Plugins.System.Exps.float,
		C3.Plugins.NinePatch.Acts.SetHeight,
		C3.Plugins.NinePatch.Acts.SetWidth,
		C3.Plugins.Text.Exps.Width,
		C3.Plugins.NinePatch.Exps.BBoxBottom,
		C3.Plugins.System.Exps.max,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Text.Acts.SetVAlign,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.System.Exps.viewportmidx,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.System.Exps.viewportwidth,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Exps.viewportmidy,
		C3.Plugins.NinePatch.Cnds.PickChildren,
		C3.Plugins.NinePatch.Exps.ColorValue,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.yagames_adaptivetext.Cnds.PickParent,
		C3.Plugins.NinePatch.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Browser.Acts.LoadStyleSheet,
		C3.Plugins.TextBox.Acts.SetText,
		C3.Plugins.Text.Cnds.IsVisible,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.TextBox.Cnds.CompareText,
		C3.Plugins.System.Exps.lowercase,
		C3.Plugins.TextBox.Exps.Text,
		C3.Plugins.Text.Cnds.CompareText,
		C3.Plugins.Dictionary.Cnds.IsEmpty
	];
};
self.C3_JsPropNameTable = [
	{AllNamesInorganic: 0},
	{AllNamesOrganic: 0},
	{ActiveNames: 0},
	{AllNames: 0},
	{HasSimilarElements: 0},
	{Answers: 0},
	{ButtonsShuffle: 0},
	{classCoor: 0},
	{OrganicSprite: 0},
	{index: 0},
	{arrayX: 0},
	{arrayY: 0},
	{SmallHeader: 0},
	{HeaderX: 0},
	{Text: 0},
	{AJAX: 0},
	{ButtonGo: 0},
	{Мышь: 0},
	{Touch: 0},
	{Dictionary: 0},
	{selected: 0},
	{Right: 0},
	{AdaptiveText: 0},
	{ButtonRed: 0},
	{ButtonUnselected: 0},
	{ButtonGreen: 0},
	{ButtonSelected: 0},
	{tag: 0},
	{Icon: 0},
	{LocalStorage: 0},
	{ScrollTo: 0},
	{"8Direction": 0},
	{Camera: 0},
	{ButtonGrey: 0},
	{Box: 0},
	{Background: 0},
	{ButtonGreenRed: 0},
	{Background2: 0},
	{enabled: 0},
	{id: 0},
	{Button: 0},
	{SliderBar: 0},
	{MistakeWas: 0},
	{Tween: 0},
	{ButtonHollow: 0},
	{TextInput: 0},
	{List: 0},
	{Browser: 0},
	{Keyboard: 0},
	{HollowSprite: 0},
	{TouchArea: 0},
	{Buttons: 0},
	{zMode: 0},
	{NumVariants: 0},
	{NamesType: 0},
	{deltaPoints: 0},
	{Question: 0},
	{CorrAnswer: 0},
	{QueX: 0},
	{QueY: 0},
	{CorrX: 0},
	{CorrY: 0},
	{Ready: 0},
	{CorrectAnswerCount: 0},
	{SectionIndex: 0},
	{Section: 0},
	{CorrCount: 0},
	{xDescription: 0},
	{xActive: 0},
	{NumActiveNames: 0},
	{NumQuestions: 0},
	{SectionTraining: 0},
	{test: 0},
	{height: 0},
	{NumberOfCorrectAnswers: 0},
	{MaxNumberOfCorrectAnswers: 0},
	{IncorrX: 0},
	{IncorrY: 0},
	{PreviusValue: 0},
	{CurrentValue: 0},
	{numberOfSimilarNames: 0},
	{IncorrX2: 0},
	{IncorrY2: 0},
	{ActiveNamesY: 0},
	{count: 0},
	{x: 0},
	{AnswerX: 0},
	{Answer: 0},
	{XMax: 0},
	{Z: 0},
	{y: 0},
	{firstY: 0},
	{lastY: 0},
	{UID: 0},
	{LayerID: 0},
	{LayerName: 0},
	{Hide: 0},
	{TrainingMode: 0},
	{PrevLayerName: 0},
	{MakePreviousLayerInvisible: 0},
	{MaxOrgNamesCount: 0},
	{MaxVariants: 0},
	{Diap0: 0},
	{Diap1: 0},
	{BottomBorderY0: 0},
	{BottomBorderY1: 0},
	{Variable1: 0},
	{CurrentPage: 0},
	{HeaderY: 0},
	{TouchTime: 0},
	{TouchHolding: 0},
	{txt: 0},
	{Small: 0},
	{TextBelowExists: 0},
	{Inorganic: 0},
	{BottomBorderY: 0},
	{ButtonGoRightX: 0},
	{ButtonGoLeftX: 0},
	{Procent: 0},
	{QuestionIndex: 0},
	{oldHeight: 0},
	{updHeight: 0},
	{RightSelected: 0},
	{SelectionIndex: 0},
	{SelectionReady: 0},
	{ChosenCounter: 0},
	{NumberOfLines: 0},
	{AllAnswersAreCorrect: 0},
	{d: 0},
	{width: 0},
	{yy: 0},
	{l: 0},
	{difference: 0},
	{yQue: 0},
	{xAns: 0},
	{xQue: 0},
	{NumCorrectAnswers: 0},
	{cut: 0},
	{counter: 0},
	{YSpawn: 0},
	{GreenR: 0},
	{GreenG: 0},
	{GreenB: 0},
	{RedR: 0},
	{RedG: 0},
	{RedB: 0},
	{MaxNumberOfAnswers: 0},
	{DSpawn: 0},
	{itemExists: 0}
];

self.InstanceType = {
	AllNamesInorganic: class extends self.IArrayInstance {},
	AllNamesOrganic: class extends self.IArrayInstance {},
	ActiveNames: class extends self.IArrayInstance {},
	AllNames: class extends self.IArrayInstance {},
	Answers: class extends self.IArrayInstance {},
	ButtonsShuffle: class extends self.IArrayInstance {},
	classCoor: class extends self.IArrayInstance {},
	OrganicSprite: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	AJAX: class extends self.IInstance {},
	ButtonGo: class extends self.ISpriteInstance {},
	Мышь: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	Dictionary: class extends self.IDictionaryInstance {},
	AdaptiveText: class extends self.IWorldInstance {},
	ButtonRed: class extends self.IWorldInstance {},
	ButtonUnselected: class extends self.IWorldInstance {},
	ButtonGreen: class extends self.IWorldInstance {},
	ButtonSelected: class extends self.IWorldInstance {},
	Icon: class extends self.ISpriteInstance {},
	LocalStorage: class extends self.IInstance {},
	Camera: class extends self.ISpriteInstance {},
	ButtonGrey: class extends self.IWorldInstance {},
	Box: class extends self.IWorldInstance {},
	Background: class extends self.ISpriteInstance {},
	ButtonGreenRed: class extends self.IWorldInstance {},
	Background2: class extends self.ISpriteInstance {},
	Button: class extends self.IWorldInstance {},
	SliderBar: class extends self.ISliderBarInstance {},
	ButtonHollow: class extends self.IWorldInstance {},
	TextInput: class extends self.ITextInputInstance {},
	List: class extends self.IListInstance {},
	Browser: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	HollowSprite: class extends self.ISpriteInstance {},
	TouchArea: class extends self.ITiledBackgroundInstance {},
	Buttons: class extends self.IWorldInstance {}
}